version: '3'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: gateway
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - api-network

networks:
  api-network:
    external: true